### ISSUE TITLE
Hero card is not displayed

### ISSUE THREAD

**Issue by xieofxie** [Azure-Samples/Cognitive-Services-Voice-Assistant#10]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Send a herocard.

### Any log messages given by the failure
>
No log. Just don't display it.

### Expected/desired behavior
>
Display it correctly.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10

### Versions
>
Latest master.

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by splumber** [comment]
Hi @xieofxie, thank you for bring this to our attention. There is no such C# SDK for rendering Bot Framework cards and no mapper to convert these cards to Adaptive Cards. [Adaptive Cards](https://adaptivecards.io/) are cross-platform and customizable and should be considered for new Bots.
