### ISSUE TITLE
Make it clear Raspbian is not supported in Docs

### ISSUE THREAD

**Issue by chschrae** [Azure-Samples/Cognitive-Services-Voice-Assistant#109]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
Raspbian is not supported and we should be explicit in the docs.

**Comment by mswellsi** [comment]
I will test Raspbian with the latest version.
So far Ubuntu 20.04 LTS is working for RPi3 and RPi 4.

**Comment by mswellsi** [comment]
It does not work, issue #402 was raised to track that, so will update the docs to close this out.
