### ISSUE TITLE
publish the Windows console executable as an "Artifact" of the pipeline

### ISSUE THREAD

**Issue by chschrae** [Azure-Samples/Cognitive-Services-Voice-Assistant#119]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

publish the Windows console executable as an "Artifact" of the ADO build pipeline. Not urgent. See for example the "Artifacts" button here: https://msasg.visualstudio.com/Skyman/_build/results?buildId=10643429

**Comment by dargilco** [comment]
Done
