### ISSUE TITLE
Unable to load DLL 'Microsoft.CognitiveServices.Speech.core.dll

### ISSUE THREAD

**Issue by xhr0804** [Azure-Samples/Cognitive-Services-Voice-Assistant#150]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>After I followed the steps in the doc, and run the VoiceAssistantClient.exe, I got an error.
And I can not find the Microsoft.CognitiveServices.Speech.core.dll in the bin\x64\Debug folder
![image](https://user-images.githubusercontent.com/44257569/77915447-146efe00-72ca-11ea-9d98-6edac3df6397.png)

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by chschrae** [comment]
Hi there,

Thanks for reporting this issue. We are able to reproduce it and should have a fix checked in soon. The fix we have is to update the nuget package for Microsoft.CognitiveServices.Speech to the 1.10 release. Could you try that and see if it works for you?

**Comment by dargilco** [comment]
Update to Speech SDK 1.10 does not fix the issue. We are working on another fix.

**Comment by xhr0804** [comment]
Copying the dll from the package folder works, thanks!
