### ISSUE TITLE
Implement "Push To Talk" or "ListenOnce" command

### ISSUE THREAD

**Issue by chschrae** [Azure-Samples/Cognitive-Services-Voice-Assistant#163]
This should be used to track the work to actually implement the functionality of a call to the ListenOnce api from the speech sdk.

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

**Comment by qfweiwei** [comment]
This functionality has already been implemented in Main.cpp by making StartListening call ListenOnceAsync when keystroke is "1".
