### ISSUE TITLE
UWPVA: Support for compressed TTS output audio in Direct Line Speech

### ISSUE THREAD

**Issue by trrwilson** [Azure-Samples/Cognitive-Services-Voice-Assistant#216]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
Direct Line Speech provides the ability to request a specific TTS output format via a configuration property, e.g. like this:

```
config.SetProperty(PropertyId.SpeechServiceConnection_SynthOutputFormat, "audio-24khz-96kbitrate-mono-mp3");
```

Versus the default 16khz, 16-bit mono PCM output, we believe something like the above mp3 container format could provide both improved quality *and* reduced bandwidth consumption. This could be particularly important in bandwidth-constrained situations, e.g. over mobile data.

DirectLineSpeechDialogBackend, DialogManager, and the related classes should get some updates to support different output formats.

**Comment by dargilco** [comment]
Travis finished the work as far as I know. Closing.
