### ISSUE TITLE
Maintain one DialogServiceConnector Object for Text and Speech Input

### ISSUE THREAD

**Issue by splumber** [Azure-Samples/Cognitive-Services-Voice-Assistant#269]
Currently, a new DialogServiceConnectorObject is created when application is Keyword Actviated.
The proposal is that the app should maintain one DialogServiceConnector object for both text and speech input if InputHint is of expectingInput
If Initial interaction is Keyword Activation and bot response inputhint is expectingInput, the connection should stay open allowing either text or speech input (without Keyword).

### This issue is for a: (mark with an `x`)
- [] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

**Comment by dargilco** [comment]
Done
