### ISSUE TITLE
Use common naming convention for variable across samples

### ISSUE THREAD

**Issue by chschrae** [Azure-Samples/Cognitive-Services-Voice-Assistant#320]
We should use a common convention for variables across all samples. We could use Win32: https://docs.microsoft.com/en-us/windows/win32/stg/coding-style-conventions

or come up with our own, but we should be consistent

I imagine this will result in an issue for each client to follow the decided convention.

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

**Comment by dargilco** [comment]
Cleaning up the board. I don't think we need this, but @chschrae please let me know if you feel strongly about this.
