### ISSUE TITLE
Update all clients to use Speech SDK 1.12 when it comes out

### ISSUE THREAD

**Issue by dargilco** [Azure-Samples/Cognitive-Services-Voice-Assistant#369]

**Comment by chschrae** [comment]
I think you mean 1.12

**Comment by mswellsi** [comment]
It is out now.

**Comment by dargilco** [comment]
Assigned to Olivier since the only one left to update is the Android Java client

**Comment by olmidy** [comment]
PR https://github.com/microsoft/botframework-solutions/pull/3418
