### ISSUE TITLE
The 'Voice Assistant supported regions' link is not helpful

### ISSUE THREAD

**Issue by wellsi** [Azure-Samples/Cognitive-Services-Voice-Assistant#395]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

On page
https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/tree/master/clients
it says
"The Azure region of your speech subscription. Limited to the Voice Assistant supported regions. "
which links to
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started

That page has no relevant information.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mswellsi** [comment]
This is the useful link

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/regions#voice-assistants
