### ISSUE TITLE
The path to cpp-console is wrong for RPi default install

### ISSUE THREAD

**Issue by wellsi** [Azure-Samples/Cognitive-Services-Voice-Assistant#396]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> git clone https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant.git

This gives the root of the local git repo on the RPI as /home/ubuntu/Cognitive-Services-Voice-Assistant
but the documentation presumes it is 
/home/ubuntu/

ubuntu@ubuntu:~/Cognitive-Services-Voice-Assistant$ pwd
/home/ubuntu/Cognitive-Services-Voice-Assistant

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mswellsi** [comment]
Can the git clone go to a specified folder, or should a symbolic link be created in the build script?

**Comment by mswellsi** [comment]
If a '.' was added then the folder structure would match the docs, and the paths are short
git clone https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant.git .

However then we get a number of files dropped into the home folder, which is not great.

**Comment by mswellsi** [comment]
Actually we need to update the docs as even dumping the git repo into the home directory does not help. The keyword models and the config have assumed different root folders. I'll update the docs.
