### ISSUE TITLE
"Reduce blue boxes by 5" results in ADDING 5 boxes

### ISSUE THREAD

**Issue by dargilco** [Azure-Samples/Cognitive-Services-Voice-Assistant#411]
Install the inventory CC demo. 

Say "Recude blue boxes by 5".

The agent replies with "5 blue boxes have been added".

Should subtract, not add.

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

**Comment by JPalmerDev** [comment]
This should solve these issues.
**Ship sample sentences**
delete
delete {WhichItem}
delete {Quantity} {WhichItem}
cross out
cross out {WhichItem}
cross out {Quantity} {WhichItem}
sell
sell {WhichItem}
sell {Quantity} {WhichItem}
reduce
reduce {WhichItem}
reduce {Quantity} {WhichItem}
Remove
Remove {WhichItem}
Remove {Quantity} {WhichItem}
Ship
Ship {WhichItem}
Ship {Quantity} {WhichItem}
take away
take away {WhichItem}
take away {Quantity} {WhichItem}
take out
take out {WhichItem}
take out {Quantity} {WhichItem}

**Comment by JPalmerDev** [comment]
I have provided Fan with a manually updated json that fixes these queries.
