### ISSUE TITLE
Linux ARM64 support

### ISSUE THREAD

**Issue by wellsi** [Azure-Samples/Cognitive-Services-Voice-Assistant#451]
> Please provide us with the following information:
> ---------------------------------------------------------------

Please provide a buildArm64Linux script as the ARM32 does not run on ARM64 platforms like NVidia Jetson Nano.

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>
Building Linux Arm32 sample ...
/usr/bin/ld: skipping incompatible ./lib/arm32/libMicrosoft.CognitiveServices.Speech.core.so when searching for -lMicrosoft.CognitiveServices.Speech.core
/usr/bin/ld: cannot find -lMicrosoft.CognitiveServices.Speech.core
collect2: error: ld returned 1 exit status
Cleaning up downloaded files
Done. To start the demo execute:

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Ubuntu 18-04
Linux jetson 4.9.140-tegra #1 SMP PREEMPT Wed Apr 8 18:10:49 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wellsi** [comment]
Now checking if it is just replacing 32 with 64 in the script

**Comment by wellsi** [comment]
Here is the error message

ubuntu@jetson:~/Cognitive-Services-Voice-Assistant/clients/cpp-console/out$ ./sample.exe ../configs/config.json
New status : Initializing
10:19:05.28  Loading configuration from file: ../configs/config.json
10:19:05.36  Configuration loaded. Creating connector...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)
[CALL STACK BEGIN]

../lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so(+0x1c0254) [0x7f980f2254]
../lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so(+0x321b70) [0x7f98253b70]
../lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so(+0x1d9400) [0x7f9810b400]
../lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so(+0x1d7bac) [0x7f98109bac]
../lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so(+0x31cdec) [0x7f9824edec]
../lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so(+0x1d9400) [0x7f9810b400]
../lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so(+0x1d7bac) [0x7f98109bac]
../lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so(+0x2ddec4) [0x7f9820fec4]
../lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so(+0x262274) [0x7f98194274]
../lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so(+0x26039c) [0x7f9819239c]
../lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so(+0x260be4) [0x7f98192be4]
../lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so(+0x26128c) [0x7f9819328c]
../lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so(+0x168348) [0x7f9809a348]
../lib/arm64/libMicrosoft.CognitiveServices.Speech.core.so(dialog_service_connector_create_dialog_service_connector_from_config+0x1cc) [0x7f98092244]
./sample.exe(+0x3ee90) [0x559399fe90]
./sample.exe(+0x3824c) [0x559399924c]
./sample.exe(+0x37f5c) [0x5593998f5c]
./sample.exe(+0x10744) [0x5593971744]
/lib/aarch64-linux-gnu/libc.so.6(__libc_start_main+0xe0) [0x7f97c156e0]
./sample.exe(+0x10214) [0x5593971214]
[CALL STACK END]

**Comment by wellsi** [comment]
So the good news is that it works - just need to sort out the mic issue.

Will look to see if the build script can be made common for ARM32/64

**Comment by wellsi** [comment]
Testing a combined build script currently. Works on ARM32, need to verify ARM64 before PR

**Comment by mswellsi** [comment]
Documenting how to use this will be in another issue and PR.
