### ISSUE TITLE
Improve error message for table file, and documentation

### ISSUE THREAD

**Issue by wellsi** [Azure-Samples/Cognitive-Services-Voice-Assistant#452]
> Please provide us with the following information:
> ---------------------------------------------------------------

There is documentation and an error message for the keyword file, but both could be improved.

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ X documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Follow RaspberryPi.md

You may follow this, and miss that the config file needs .../keyword.table
The keyword_model should point to the Custom Keyword being used (.table file), these are in /home/ubuntu/Cognitive-Services-Voice-Assistant/keyword-models

### Any log messages given by the failure
>
ubuntu@jetson:~/Cognitive-Services-Voice-Assistant/clients/cpp-console/out$ ./sample.exe ../configs/config.json
New status : Initializing
10:07:07.105  Loading configuration from file: ../configs/config.json
10:07:07.115  Keyword file extension is not ".table".

### Expected/desired behavior
>

1) Documentation could give an example showing full path
2) Error message could echo the current value of "KeywordRecognitionModel"

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mswellsi** [comment]
This is the relevant code block, and an error message is returned, but it would help if in both these error cases if the current setting of 'keywordRecognitionModel' is also printed.

    if (config->_keywordRecognitionModel.length() > 0)
    {
        if (!std::experimental::filesystem::exists(config->_keywordRecognitionModel))
        {
            config->_loadResult = AgentConfigurationLoadResult::KWFileNotFound;
            return config;
        }

        // this check should be removed once the SDK properly validates KWS model files
        std::experimental::filesystem::path pathObj(config->_keywordRecognitionModel);
        if (!pathObj.has_extension() || pathObj.extension().string() != ".table")
        {
            config->_loadResult = AgentConfigurationLoadResult::KWFileWrongExtension;
            return config;
        }
    }
