### ISSUE TITLE
How can I use zh-chs-XiaoyouNeural

### ISSUE THREAD

**Issue by 44886** [Azure-Samples/Cognitive-Services-Voice-Assistant#462]
![image](https://user-images.githubusercontent.com/10481933/83583661-85a38980-a577-11ea-87ad-e8955431d4da.png)

I can use  zh-CN-XiaoxiaoNeural

But can not use these:
![image](https://user-images.githubusercontent.com/10481933/83583702-a53ab200-a577-11ea-9dc5-6083423cd052.png)

**Comment by dargilco** [comment]
@44886 can you tell me which client application are you using? Have you written a bot or are you using a Custom Command project?

**Comment by 44886** [comment]
I got it

the list  show me this:
![image](https://user-images.githubusercontent.com/10481933/83587927-c81e9380-a582-11ea-916d-439473cc16b0.png)

The docs is worning.

**Comment by dargilco** [comment]
You are right, seems like the en-us docs page is correct, but the zn-ch is not. I will contact the text to speech team to fix the documentation right away. Thanks!
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#neural-voices
https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/language-support#neural-voices
