### ISSUE TITLE
 Suggestion of moving the  "this.player.Init(entry.Reader); " under the thread lock

### ISSUE THREAD

**Issue by lcrun** [Azure-Samples/Cognitive-Services-Voice-Assistant#474]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting

```

### Minimal steps to reproduce
> Play audio un multiple threads

### Any log messages given by the failure
>

### Expected/desired behavior
>
    private bool PlayFromAudioQueue()
        {
            WavQueueEntry entry = null;
            lock (this.playbackStreams)
            {
                if (this.playbackStreams.Count > 0)
                {
                    entry = this.playbackStreams.Peek();
                }
            }

            if (entry != null)
            {
                System.Diagnostics.Debug.WriteLine($"START playing {entry.Id}");
                this.player.Init(entry.Reader);
                this.player.Play();
                return true;
            }

            return false;
        }

=>
        private bool PlayFromAudioQueue()
        {
            WavQueueEntry entry = null;
            lock (this.playbackStreams)
            {
                if (this.playbackStreams.Count > 0)
                {
                    entry = this.playbackStreams.Peek();
                }

                if (entry != null)
                {
                    System.Diagnostics.Debug.WriteLine($"START playing {entry.Id}");
                    this.player.Init(entry.Reader);
                    this.player.Play();
                    return true;
                }
            }

            return false;
        }

### OS and Version?
> Windows 10

### Versions
> Windows 10 Version 1909 for x64-based Systems

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by splumber** [comment]
Hi @lcrun can you please elaborate on the issue, what is the reasoning behind adding this Thread Lock?

**Comment by dargilco** [comment]
Closing since there was no response
