### ISSUE TITLE
Direct Line Speech channel is not working with NodeJS Basic bot

### ISSUE THREAD

**Issue by varunbmallik** [Azure-Samples/Cognitive-Services-Voice-Assistant#480]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Create a NodeJS basic bot (not echo bot)
Setup DirectLineSpeech channel and map a speech service (westus2 region) to the bot
Host the bot on Azure web app host

### Any log messages given by the failure
> No log of errors in browser. Voice input is taken but is it not connecting to the bot. There is no response from the bot

### Expected/desired behavior
>Bot should taken user voice input and internally connect to the bot and respond with the conversational flow that has been setup in the bot

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows and Mac Chrome browsers
### Versions
>

### Mention any other details that might be useful
Attaching the html file for hosting the bot in Azure webapp host.
[BotwithDLSSpeechChannel.txt](https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/files/4769992/BotwithDLSSpeechChannel.txt)

This works as expected in echo bot but the same doesn't work for the bot built using basic bot template. I had raised the same issue with Microsoft support and I was suggested to add the below piece of code in bot's index.js file because there was some issue with the websockets.

// Listen for Upgrade requests for Streaming.
server.on('upgrade', (req, socket, head) => {
    // Create an adapter scoped to this WebSocket connection to allow storing session data.
    const streamingAdapter = new BotFrameworkAdapter({
        appId: process.env.MicrosoftAppId,
        appPassword: process.env.MicrosoftAppPassword
    });
    // Set onTurnError for the BotFrameworkAdapter created for each connection.
    streamingAdapter.onTurnError = onTurnErrorHandler;

    streamingAdapter.useWebSocket(req, socket, head, async (context) => {
        // After connecting via WebSocket, run this logic for every request sent over
        // the WebSocket connection.
        await bot.run(context);
    });
});

and replace this line,  "adapter.onTurnError = async (context, error) =>" with "const onTurnErrorHandler = async (context, error) =>"

Using this, DLS channel worked as expected but impacted other things. Choice prompt buttons are not rendering if this new code is added to bot's index.js. Microsoft support team suggested I raise an issue in Gitub directly

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dargilco** [comment]
Hi @varunbmallik thanks for opening this issue. Is your Java Script client getting a connection cancelled event when the bot tries to send a Choice prompt card? If so, can you share all the details in the event args? Thanks!
https://docs.microsoft.com/en-us/javascript/api/microsoft-cognitiveservices-speech-sdk/dialogserviceconnector?view=azure-node-latest#canceled
https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechrecognitioncanceledeventargs?view=azure-dotnet

**Comment by varunbmallik** [comment]
Thanks @dargilco for writing back.
There is no error as such when the bot tries to send Choice prompt card. Bot is rendering the choice prompt as string values with serial numbers. Example below
Code:
await stepContext.prompt(CHOICE_PROMPT, {
            prompt: 'xyz dialog options',
            choices: ChoiceFactory.toChoices(['Option 1', 'Option 2'])
        });
This is rendering as
xyz dialog options (1) Option 1 or (2) Option 2

**Comment by dargilco** [comment]
Hi @varunbmallik, if you are not getting any errors from Direct Line Speech, then this is a rendering issue with WebChat. It looks like WebChat does not support displaying choice prompt card. Please open a GitHub issue on the [BotFramework-WebChat repo](https://github.com/microsoft/BotFramework-WebChat). This is their document related to [Direct Line Speech and WebChat](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/DIRECT_LINE_SPEECH.md). Once you opened the issue, please paste the link here and I will notify the relevant folks immediately so you can get a prompt response.

**Comment by dargilco** [comment]
Also @varunbmallik, if you register the same bot with Direct Line (not Direct Line Speech) and deploy a WebChat to do text input/output conversation with your bot, does the choice prompt card get displayed as expected by WebChat? I'm trying to figure out if there is lack of support choice cards regardless of which channel you connect to, or is this issue unique to bots connected via Direct Line Speech

**Comment by varunbmallik** [comment]
Hi @dargilco , I have used the same bot with Direct Line channel and hosted it on Azure web app host. The choice prompts are rendering properly in this case. I have also added the same speech service using the webSpeechPonyfillFactory while rendering the bot and the voice input and output works as expected. However, this has an issue with selectVoice parameter to change the bot's voice but that's a different issue altogether. 
So, the issue with choice prompt not rendering seems very specific to DLS channel method. Do you suggest I still raise an issue on the other link you shared?

**Comment by dargilco** [comment]
@varunbmallik Yes please raise a GitHub Issue in the BotFramework-WebChat repo. Post a link here and tag me and I will talk to the owners of WebChat to investigate if this is a WebChat limitation or Direct Line Speech bug. Thanks!

**Comment by varunbmallik** [comment]
@dargilco Hi Darren, I have raised another issue on Webchat as suggested. Please find the link below
[BotFramework-WebChat/issues/3263](https://github.com/microsoft/BotFramework-WebChat/issues/3263)

**Comment by dargilco** [comment]
Thanks @varunbmallik I started an internal thread with Bot-Framework folks to figure this out. Let's continue the discussion in the new issue you opened. Closing this one for now.

**Comment by dargilco** [comment]
@varunbmallik one more comment - please try to use [Adaptive Cards](https://www.adaptivecards.io/) for all your needs instead of Bot-Framework cards.
