### ISSUE TITLE
Issue while connecting to speech services api using windows voice assistant client

### ISSUE THREAD

**Issue by fayaz-svg** [Azure-Samples/Cognitive-Services-Voice-Assistant#487]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>
Channel: Error (ConnectionFailure) : WebSocket Upgrade failed with HTTP status code: 200 SessionId: 
### Expected/desired behavior
>
Windows voice assistant client should connect after entering the region and subscription key for speech services api.
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by fayaz-svg** [comment]
Hi Anyone,this configuration which needs to be implemented on an urgent basis, can anyone please respond.

**Comment by dargilco** [comment]
@fayaz-svg please make sure to follow [all the steps in this page](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0) to make sure web-socket connection is enabled and supported by your bot.
Darren

**Comment by dargilco** [comment]
Also, @fayaz-svg I'm assuming you've read [this tutorial](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/tutorial-voice-enable-your-bot-speech-sdk)?

**Comment by fayaz-svg** [comment]
@dargilco : thank you so much for your help. The issue relate to websocket has been resolved by following the below link
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0
