### ISSUE TITLE
[Question] Connect to local bot

### ISSUE THREAD

**Issue by hraz-msft** [Azure-Samples/Cognitive-Services-Voice-Assistant#488]
Is there any way to connect to local bot via Bot Framework Emulator, instead of published bot?

**Comment by dargilco** [comment]
Hi @hraz-msft, I recommend you use [Windows Voice Assistant Client](https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/tree/master/clients/csharp-wpf) for testing bots that are written for voice-input/voice-output interactions. There is a way to run (and debug) your bot locally, while using Windows Voice Assistant client as your client application. It will require a tunneling software like ngrok, where a service (ngrok or other) is registered as the "bot" in the Direct Line Speech channel registration page on Azure, and that service redirects the calls back to your client which runs the actual bot. I will try to write up a  page about it today or tomorrow and post it.

**Comment by hraz-msft** [comment]
Yes, can I test the voice interactions of local bot?

**Comment by dargilco** [comment]
@hraz-msft, I just posted this article. Let me know if this is what you were looking for:
https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/blob/master/docs/LocalBot.md

Darren
