### ISSUE TITLE
Custom Commands App fails to train in the portal with error "Train Application Failed. Internal Error"

### ISSUE THREAD

**Issue by manish-95** [Azure-Samples/Cognitive-Services-Voice-Assistant#512]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> This happens to me only on certain applications. I am able to train one application, but not another. 

### Any log messages given by the failure
>

### Expected/desired behavior
> The application must train, or give a more descriptive error

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10
### Versions
>

### Mention any other details that might be useful
![image](https://user-images.githubusercontent.com/29098159/90034014-bc1b2480-dcdd-11ea-993c-bf226a263b23.png)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by manish-95** [comment]
Closing this since there was a small error in the example sentences where an extra '}' was inserted. However, it would help if the error was explicitly pointed out.

**Comment by dargilco** [comment]
Thanks for your comment @manish-95. I'll follow up with the Custom Commands team regarding your request for a more detailed error description. 
Darren.
