### ISSUE TITLE
Giving speech input from python for hospitality demo

### ISSUE THREAD

**Issue by gayalkuruppu** [Azure-Samples/Cognitive-Services-Voice-Assistant#521]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
> I need to call the speech.microsoft from a python code which is in local and control the simulation (using API calls)

### OS and Version?
> macOS (Catalina)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dargilco** [comment]
Thank you for your comment @gayalkuruppu. As you've seen, unfortunately there is currently no Python support for the dialog name space in the Speech SDK. I've communicated your request to the speech SDK team. It will not be available anytime soon so you will have to use another programming language if you plan to use Speech SDK.

**Comment by dargilco** [comment]
@gayalkuruppu, and if you have other issues/questions regarding Speech SDK, feel free to post an issue here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues

**Comment by oscarheygds** [comment]
Hi any update on this? is there any plan on supporting it
