### ISSUE TITLE
Can't connect, I am getting error 500 

### ISSUE THREAD

**Issue by pedro-ramirez-suarez** [Azure-Samples/Cognitive-Services-Voice-Assistant#522]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Connect an existing bot to speech services and test with VoiceAssistantClient application. My bot uses a lot of HeroCards to interact with the user, it's already working and I have integrated my bot into my website. I am trying to voice-enable my bot, I followed the intructions on https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/tutorial-voice-enable-your-bot-speech-sdk and when I try to test my bot with the VoiceAssistantClient I got the following error:

Error (ConnectionFailure) : Connection was closed by the remote host. Error code: 1002. Error details: The server returned status code '500' when status code '101' was expected. SessionId: 6e72f94575484dd2bf94565141f45294

I already went through the troubleshooting section in https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/blob/master/clients/csharp-wpf/README.md without success. 

### Any log messages given by the failure
>Error (ConnectionFailure) : Connection was closed by the remote host. Error code: 1002. Error details: The server returned status code '500' when status code '101' was expected. SessionId: 6e72f94575484dd2bf94565141f45294

### Expected/desired behavior
> I expect to be able to connect successfully and test my bot. 

### OS and Version?
> Windows 10 Enterprise running VM running on Parallels macOS Catalina 

### Versions
>

### Mention any other details that might be useful
The region that I am using (eastus) supports  Neural Voices.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by chschrae** [comment]
@pedro-ramirez-suarez  Hi there,

One thing that I have run into in the past is that the appid and password were different in the app from what was in the Azure portal. Can you please verify in the Web App Bot -> settings azure blade the App ID is the same as the one in the App Service -> configuration blade and the same as the one in your appsettings.json within the c# project?

**Comment by pedro-ramirez-suarez** [comment]
Hi, thanks for the reply, It's the same ID, I was able to make it work, at some point (right now I don't remember the step) when you are creating an Azure resource there is a checkbox to indicate if there is already a bot connected, the first time I missed that and didn't click on it; I created a new resource and this time I click on the checkbox and it worked.

**Comment by chschrae** [comment]
@pedro-ramirez-suarez OK great! I'm glad you were able to get it working.
