### ISSUE TITLE
Unable to connect. Error code: 1002. The server returned status code '405'

### ISSUE THREAD

**Issue by sereilly** [Azure-Samples/Cognitive-Services-Voice-Assistant#523]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Followed the steps at https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/tutorial-voice-enable-your-bot-speech-sdk to add voice support to my bot. Only difference is I'm using bot sample 63 instead of 02 since it also contains a Twilio adapter.

I haven't been able to find any instances of others getting this particular status code.

### Any log messages given by the failure
>

Error (ConnectionFailure) : Connection was closed by the remote host. Error code: 1002. Error details: The server returned status code '405' when status code '101' was expected. SessionId: ecf282bbb759438e8dd6fb93a6db3ac5

### Expected/desired behavior
>

Voice Assistance Client connects successfully.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Windows 10

### Versions
>

Voice Client v1.11.0

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dargilco** [comment]
@sereilly , can you check if sample 63 was modified to suppor Direct Line Speech, as per [this document](https://docs.microsoft.com/en-us/azure/bot-service/directline-speech-bot?view=azure-bot-service-4.0#:~:text=APPLIES%20TO%3A%20SDK%20v4.%20Direct%20Line%20Speech%20uses,to%20listen%20for%20and%20accept%20these%20WebSocket%20connections.)? The Echo bot was updated to make sure it supports Direct Line Speech. I'm not sure the same applies to sample 63.
Darren

**Comment by dargilco** [comment]
@sereilly I would also first make sure you get it to work with the Echo Bot, then try with another bot. Just want to make sure the instructions as they are work for you with the Echo bot before we discuss switching to another bot.

**Comment by sereilly** [comment]
That was it! I added .UseWebSockets() to Configure and [HttpGet] to PostAsync in sample 63 and now it works.

**Comment by dargilco** [comment]
@sereilly, that's good to hear. I'll make sure we update the [voice-enable-your-bot tutorial](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/tutorial-voice-enable-your-bot-speech-sdk) to highlight what to do if you are using another bot. The link is mentioned at the very end at the "See also" section ("Build a Bot Framework bot. Register it with Direct Line Speech channel and customize your bot for voice"), but there should be a separate section before this one toward the end about this as it's easy to miss.
