### ISSUE TITLE
Custom Commands LUIS prediction resource not deployed with ps script

### ISSUE THREAD

**Issue by chschrae** [Azure-Samples/Cognitive-Services-Voice-Assistant#525]
> Please provide us with the following information:
> ---------------------------------------------------------------

This became available in v1.0 of the CC API's

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Run the powershell script to deploy a CC project
See in the speech portal that the luis prediction key is not set.

**Comment by MrHamlet** [comment]
Deprecating custom commands.

**Comment by MrHamlet** [comment]
Deprecating custom commands.

**Comment by MrHamlet** [comment]
Deprecating custom commands.
