### ISSUE TITLE
Send custom information to the BOT from cpp-console.

### ISSUE THREAD

**Issue by albanoandrea** [Azure-Samples/Cognitive-Services-Voice-Assistant#558]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
We would like to be able to send from the cpp-console to the Bot some information to take decisions based on the device status.
E.g.
Imagine that on the same device that runs the cpp-console there is a light, that can be turn on and off also locally.
The user tell "can you turn on the light", the Bot answer:
- "Yes, here it is" if the light was off.
-  "The light is already on" if the light was on.

This is a semplification of the use case, but it means that when the audio streaming session begin, we need to send togheter a status information to tell the BOT if the light is on or off.

Alternatevely, we would need to send to the BOT at least a "token" when the connection happens.
This "token" is needed to be associated to the session and the BOT should be able to retreive it every time onMessageActivityAsync is called.
This "token" will allow the BOT to take the information from a third party service.

There is anything like this that is feasible with the current SDK?

### OS and Version?
Linux, cpp-console.

**Comment by dargilco** [comment]
@albanoandrea This is already supported. You can define an "Activity Template", which is a JSON activity that will be sent to the Bot together with the speech recognition result, next time there is a recognition result. You can call that API anytime during your connection with the bot. 
https://docs.microsoft.com/en-us/cpp/cognitive-services/speech/dialog-dialogserviceconnector#setspeechactivitytemplate
Unfortunately, I see that we don't yet have a public sample for it. 
Try it out and feel free to ask questions here.
Darren

**Comment by dargilco** [comment]
@albanoandrea Just to add... so you can either use SendActivityAsync to send data up to the bot anytime, unrelated to speech recognition activity. Or you can use SetSpeechActivityTemplate, if you want to send data up to the bot, and have it arrive together with the next speech recognition result
https://docs.microsoft.com/en-us/cpp/cognitive-services/speech/dialog-dialogserviceconnector#sendactivityasync 
https://docs.microsoft.com/en-us/cpp/cognitive-services/speech/dialog-dialogserviceconnector#setspeechactivitytemplate

**Comment by albanoandrea** [comment]
@dargilco 
Tank you for the hints.
We need data to arrive together with the speech recognition result, so we will use the setSpeechActivityTemplate.
There is any limitation on the string we can send to the bot? It need to be a Json string or can be any?

And, on the other side, where we would expect this info on the bot side?

When a message arrive we have this callback (from the echo example)
```
        protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            var replyText = $"Echo: {turnContext.Activity.Text}";
            Activity my_activity = MessageFactory.Text(replyText, replyText);
            await turnContext.SendActivityAsync(my_activity, cancellationToken);
        }
```
Looking for documentation of turnContext we have found this:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.connector.imessageactivity?view=botbuilder-dotnet-3.0
But can't find any reference to an ActivityTemplate or so on.

Can you please help us in finding further documentation or help us in understanding this better?
