### ISSUE TITLE
Multiple Keywords for activating the bot 

### ISSUE THREAD

**Issue by ridasaleem0** [Azure-Samples/Cognitive-Services-Voice-Assistant#574]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Using https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/keyword-recognition-overview procedure to recognize my system with single keyword detection model. I am on lookout for multiple keyword models to recognize the same device.

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
So basically I am looking for a solution or an idea about whether we can us multiple Keywords to recognize or wake our device, in this particular case device would be Microsoft Bot. 
I am using the standard keyword recognition feature that Microsoft provides but I want multiple keyword models  to be used to start the system. 
Any kind of help would be appreciated. Thank you. 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dargilco** [comment]
Thank you, Rida, for your question. Multiple keyword activation is a feature requested by others as well. It is in our backlog. The development team is currently focused on improving the quality of single keyword activation but plans to support multiple keyword activation early next year.
