### ISSUE TITLE
Azure cognitive speech to text API failing - bad request 400

### ISSUE THREAD

**Issue by carbonrider** [Azure-Samples/Cognitive-Services-Voice-Assistant#580]
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Using sample program (Java) to evaluate Speech to Text service

### Any log messages given by the failure
> Following log message is dispalyed
WebSocket upgrade failed: Bad request (400). Please verify the provided subscription details and language information.

### Expected/desired behavior
> Should able to invoke Speech To Text API

### OS and Version?
> Windows 11

### Versions
> Azure cognitiveservices speech - 1.20.0

### Mention any other details that might be useful
I verified the keys and region in Azure portal and everything is correct.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by chschrae** [comment]
closing as this has been waiting for a response for more than 14 days

**Comment by carbonrider** [comment]
Thanks, it didn't work. The error continued and we shifted to RevAI. We have been using AWS, GCP AI etc services and it doesn't have so much of hassle.

**Comment by chschrae** [comment]
@carbonrider I'm sorry you weren't able to get it to work. If you would like to continue debugging it with us, we would be happy to try and figure out the issue. Otherwise, I'm happy you were able to find a solution and I will just leave the issue closed.
