### ISSUE TITLE
Add Custom Commands application as a skill in Bot framework composer application

### ISSUE THREAD

**Issue by ridasaleem0** [Azure-Samples/Cognitive-Services-Voice-Assistant#581]
The documentation (https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-custom-commands-integrate-remote-skills) gives an idea about how to export the Custom Commands application as a skill, however, there is no skills tab available in the Speech studio under Custom commands settings.

Is there a way to export our commands app as a skill inside the bot framework application?

**Comment by ridasaleem0** [comment]
@chschrae

**Comment by chschrae** [comment]
Hi there, I've contacted the custom commands team and they should respond shortly.

**Comment by aazeez442** [comment]
Hi @ridasaleem0, 

The "Remote Skill" feature is a private preview feature in development hence not available in the Speech Portal. To better assist you with your use case, kindly reach out to us with more details at: 
vi-feedback@microsoft.com

Best
Azeez  
Program Manager - Custom Commands
