### ISSUE TITLE
Support for Prompt Calls

### ISSUE THREAD

**Issue by Amintasn** [Azure-Samples/Cognitive-Services-Voice-Assistant#71]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
return await stepContext.PromptAsync(nameof(ChoicePrompt),
                   new PromptOptions
                   {
                       Prompt = stepContext.Context.Activity.CreateReply(message),
                       Choices = new[]
                       {
                            new Choice {Value = "Yes", Synonyms = new List<string> {"yeah","ok"}},
                            new Choice {Value = "No", Synonyms = new List<string> {"never"}}
                       }.ToList(),
                       Style = ListStyle.HeroCard
                   });

### Any log messages given by the failure
No. 
The Direct Line speech client app just don't display it.
However, the application responds to user inputs regarding the prompt question like 'Yes'

### Expected/desired behavior
>To see the prompt message e.g. https://binged.it/2FlaHsh

### OS and Version?
> Windows 10 + Botframework 

### Versions
> Windows: version 1909 
> Botframework: V4.7.0

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by splumber** [comment]
Hi @Amintasn, thank you for bring this to our attention. There is no such C# SDK for rendering Bot Framework cards and no mapper to convert these cards to Adaptive Cards. Adaptive Cards are cross-platform and customizable and should be considered for new Bots.
