### ISSUE TITLE
Web client sample

### ISSUE THREAD

**Issue by theconvchamp** [Azure-Samples/Cognitive-Services-Voice-Assistant#72]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
Any plans on releasing a web client sample so also mac users (who don't want to deploy Java) can use it?

**Comment by dargilco** [comment]
Hi @theconvchamp, thanks for your comment. The Java Script version of  Speech SDK has been updated to support the dialog APIs that will allow you to host a web client that communicates with a Bot-Framework bot or Custom Command application. We do not yet have a quick start or a public sample, but we are working on it. You should be able to figure out how to use it based on the other Speech SDK JS examples (for example, for doing speech recognition). See:
https://docs.microsoft.com/en-us/javascript/api/overview/azure/speech-service?view=azure-node-latest
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/javascript
And other C# code in this repo for examples of using the dialog APIs.
Note that the JS dialog APIs do not support keyword activation. So if you need keyword activations, you will need to use a different programming language.
Darren
