### ISSUE TITLE
Action.Submit is not supported in VoiceAssistantClient

### ISSUE THREAD

**Issue by xieofxie** [Azure-Samples/Cognitive-Services-Voice-Assistant#85]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 
send an adaptive card with Action.Submit and click https://adaptivecards.io/explorer/Action.Submit.html

### Any log messages given by the failure
> 
It pops up a window
![image](https://user-images.githubusercontent.com/2876650/76952029-6d907680-6947-11ea-9a8a-f43b3eaaf21c.png)

### Expected/desired behavior
>
send back to bot

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Windows 10

### Versions
> 
Today's master

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by chschrae** [comment]
Hi there,

This is actually the intended behavior of this field. Depending on the end to end scenario, we expect developers might want to trigger different kinds of behavior with different adaptive cards. It is possible to send an activity back to your bot if you wish by changing the event handler in the code to call the SendActivityAsync method on the DialogServiceConnector object.

You can read about the adaptive card actions in .NET WPF here: https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/net-wpf/actions

**Comment by xieofxie** [comment]
@chschrae Thanks! I modify it like StatusBox_KeyUp
```
var bfActivity = Activity.CreateMessageActivity();
bfActivity.Text = submitAction.Data.ToString();
if (!string.IsNullOrEmpty(this.settings.RuntimeSettings.FromId))
{
    bfActivity.From = new ChannelAccount(this.settings.RuntimeSettings.FromId);
}

var jsonConnectorActivity = JsonConvert.SerializeObject(bfActivity);
this.Messages.Add(new MessageDisplay(bfActivity.Text, Sender.User));
this.Activities.Add(new ActivityDisplay(jsonConnectorActivity, bfActivity, Sender.User));
string id = this.connector.SendActivityAsync(jsonConnectorActivity).Result;
Debug.WriteLine($"SendActivityAsync called, id = {id}");
```
And it works. Will you add an example to the document? It will save time.

**Comment by chschrae** [comment]
Addressed this is https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/pull/93
