### ISSUE TITLE
Do not show green bubble for empty text in VoiceAssistantClient 

### ISSUE THREAD

**Issue by xieofxie** [Azure-Samples/Cognitive-Services-Voice-Assistant#92]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

Send an activity with empty text (maybe have cards etc.)

### Any log messages given by the failure
>

### Expected/desired behavior
>

Do not show the green bubble 
![image](https://user-images.githubusercontent.com/2876650/77037216-c9144000-69eb-11ea-9435-0eb9ec6a60c4.png)

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Windows 10

### Versions
>

Today master

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by chschrae** [comment]
Hi there,

The bubbles should only appear on message type activities or activities with cards to be rendered. If you want an activity without the bubble simply send one of a different type. This can be useful if you want to trigger something on the client without showing anything. You can see where the bubbles are displayed in MainWindow.xaml.cs around lines 429-440.

**Comment by xieofxie** [comment]
Hi @chschrae, I create a pr to explain my expectation: https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/pull/94

Please take a look, thanks~
